### ISSUE TITLE
Latest update for 1.21.1 support doesn't work

### ISSUE THREAD

**Issue by ddirodoku** [Trivaxy/Tiny-Item-Animations#16]
![Screenshot 2024-08-19 135616](https://github.com/user-attachments/assets/c7f78044-39d1-4ece-9080-24a233beb67b)
I ran the mod alone to make sure it wasn't a confliction on my end, but it still didn't load. I don't know much about modding but figured I'd make it known!

**Comment by ixradioactivexi** [comment]
I have a fix. open the mod in 7zip, extract fabric.mod.json, then change line 28 from    "minecraft": "[1.21, 1.21.1]",    to "minecraft": "~1.21",

**Comment by ddirodoku** [comment]
I’ll give that a try when I get the chance!

**Comment by Trivaxy** [comment]
woops, i ended up uploading misconfigured builds to modrinth. it should be fixed now, please test it out and let me know.

**Comment by ddirodoku** [comment]
Works fine now! Appreciate the quick fix
