### ISSUE TITLE
1.20 update

### ISSUE THREAD

**Issue by Ultimushadow** [Trivaxy/Tiny-Item-Animations#6]
Hey there, I wanted to ask if you plan on updating to 1.20? I really appreciate the small things like this and would love to see it updated

**Comment by Trivaxy** [comment]
I have the ports ready for 1.20. I'll have them uploaded by today or tomorrow.

**Comment by Ultimushadow** [comment]
Thanks for the update!

**Comment by Trivaxy** [comment]
@Ultimushadow Updated the mod to 1.20 - it's on curseforge and modrinth now 👍
